from conf import task_model, dialogue_model
from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIChatModelSettings

abox_agent = Agent(task_model,
    system_prompt="You are an ABox Agent. Your task is to receive an answer to a question and extract data from it"
                  "according to the specified output format",
    model_settings= OpenAIChatModelSettings(temperature=0.2),
    retries=3
)

tbox_agent = Agent(dialogue_model,
    system_prompt="You are a TBox Agent. Your task is to generate a coherent one_to_one to guide a data generation"
                  "process based on it",
    model_settings=OpenAIChatModelSettings(temperature=0.5),
    retries=3
)

repair_agent = Agent(dialogue_model,
    system_prompt="You are an agent tasked with the repair of a one_to_one generated by another agent according to the"
                  "errors you will be given",
    model_settings=OpenAIChatModelSettings(temperature=0.1),
    retries=3
)

parser_agent = Agent(task_model,
    system_prompt="You are an agent dedicated to extracting data from questions. Your job is to take a question and"
                  "extract the data you find in it according to the output model given to you.",
    model_settings=OpenAIChatModelSettings(temperature=0.15, max_tokens=4096),
    retries=3
)

cluster_agent = Agent(task_model,
    system_prompt="You are a clustering agent, your task is to take a series of intents and group them into areas of"
                  "expertise coherent with their function",
    model_settings=OpenAIChatModelSettings(temperature=0.1),
    retries=3
)

